//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intersect.Framework.Core.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Intersect.Framework.Core.Properties.CoreStrings", typeof(CoreStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DescriptorType_Animation {
            get {
                return ResourceManager.GetString("DescriptorType_Animation", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Animation_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_Animation_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Class {
            get {
                return ResourceManager.GetString("DescriptorType_Class", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Class_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_Class_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Item {
            get {
                return ResourceManager.GetString("DescriptorType_Item", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Item_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_Item_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Npc {
            get {
                return ResourceManager.GetString("DescriptorType_Npc", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Npc_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_Npc_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Projectile {
            get {
                return ResourceManager.GetString("DescriptorType_Projectile", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Projectile_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_Projectile_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Quest {
            get {
                return ResourceManager.GetString("DescriptorType_Quest", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Quest_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_Quest_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Resource {
            get {
                return ResourceManager.GetString("DescriptorType_Resource", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Resource_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_Resource_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Shop {
            get {
                return ResourceManager.GetString("DescriptorType_Shop", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Shop_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_Shop_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Spell {
            get {
                return ResourceManager.GetString("DescriptorType_Spell", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Spell_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_Spell_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_CraftTables {
            get {
                return ResourceManager.GetString("DescriptorType_CraftTables", resourceCulture);
            }
        }
        
        internal static string DescriptorType_CraftTables_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_CraftTables_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Crafts {
            get {
                return ResourceManager.GetString("DescriptorType_Crafts", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Crafts_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_Crafts_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Map {
            get {
                return ResourceManager.GetString("DescriptorType_Map", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Map_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_Map_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Event {
            get {
                return ResourceManager.GetString("DescriptorType_Event", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Event_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_Event_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_PlayerVariable {
            get {
                return ResourceManager.GetString("DescriptorType_PlayerVariable", resourceCulture);
            }
        }
        
        internal static string DescriptorType_PlayerVariable_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_PlayerVariable_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_ServerVariable {
            get {
                return ResourceManager.GetString("DescriptorType_ServerVariable", resourceCulture);
            }
        }
        
        internal static string DescriptorType_ServerVariable_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_ServerVariable_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Tileset {
            get {
                return ResourceManager.GetString("DescriptorType_Tileset", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Tileset_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_Tileset_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Time {
            get {
                return ResourceManager.GetString("DescriptorType_Time", resourceCulture);
            }
        }
        
        internal static string DescriptorType_Time_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_Time_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_GuildVariable {
            get {
                return ResourceManager.GetString("DescriptorType_GuildVariable", resourceCulture);
            }
        }
        
        internal static string DescriptorType_GuildVariable_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_GuildVariable_Plural", resourceCulture);
            }
        }
        
        internal static string DescriptorType_UserVariable {
            get {
                return ResourceManager.GetString("DescriptorType_UserVariable", resourceCulture);
            }
        }
        
        internal static string DescriptorType_UserVariable_Plural {
            get {
                return ResourceManager.GetString("DescriptorType_UserVariable_Plural", resourceCulture);
            }
        }
    }
}
