//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intersect.Framework.Runtime.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AssetManagerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssetManagerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intersect.Framework.Runtime.Assets.AssetManagerResources", typeof(AssetManagerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding an asset loader that was already registered and not completely removed..
        /// </summary>
        internal static string AddLoader_AddingAnAssetLoaderThatWasNotCompletelyRemoved {
            get {
                return ResourceManager.GetString("AddLoader_AddingAnAssetLoaderThatWasNotCompletelyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to load &quot;{AssetName}&quot; of type &quot;{AssetType}&quot; but there was a conflicting asset of type &quot;{ExistingAssetType}&quot; for the qualified asset name &quot;{QualifiedAssetName}&quot;..
        /// </summary>
        internal static string TryGet_LogError_ConflictingAssetOfDifferentType {
            get {
                return ResourceManager.GetString("TryGet_LogError_ConflictingAssetOfDifferentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load &quot;{AssetName}&quot; of type &quot;{AssetType}&quot;..
        /// </summary>
        internal static string TryGet_LogWarning_CouldNotLoadAsset {
            get {
                return ResourceManager.GetString("TryGet_LogWarning_CouldNotLoadAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no loader registered for &quot;{AssetType}&quot; in order to load &quot;{AssetName}&quot;..
        /// </summary>
        internal static string TryGet_LogWarning_NoLoaderForType {
            get {
                return ResourceManager.GetString("TryGet_LogWarning_NoLoaderForType", resourceCulture);
            }
        }
    }
}
